# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14
    #command: postgres -c logging_collector=on -c log_min_duration_statement=0 -c log_directory='/var/log/postgresql'
    ports:
      - "5402:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf

volumes:
  pg_data: {}
