/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shared;

import static org.junit.jupiter.api.Assertions.*;

import domain.ConwaysGameOfLife.Cell;
import domain.ConwaysGameOfLife.GameOfLife;
import domain.ConwaysGameOfLife.GridState;
import java.util.HashSet;
import java.util.Set;
import org.junit.jupiter.api.Test;

class GameOfLifeTest {
    @Test
    void iceDisplay() {
        Set<Cell> liveCells = new HashSet<>();
        liveCells.add(new Cell(1, 1));
        liveCells.add(new Cell(1, 2));
        liveCells.add(new Cell(1, 3));
        liveCells.add(new Cell(2, 3));

        GridState previouState = new GridState(5, 15, liveCells, 0);

        System.out.println("Generation " + previouState.getGenerationNumber());
        System.out.println(GridState.display(previouState));

        for (var i = 0; i < 5; i++) {
            var e = new GameOfLife.GenerationAdvanced();
            var state2 = e.apply(previouState);

            System.out.println("Generation " + state2.getGenerationNumber());
            System.out.println(GridState.display(state2));
            previouState = state2;
        }
    }
}
